networks:
  ai-network:

services:
  ai:
    build:
      context: ./src
      dockerfile: ai.dockerfile
    container_name: ai
    ports:
      - 5555:5555
    env_file:
      - ./.env
    volumes:
      - ./src:/app
    networks:
      - ai-network